Software/Python/easygopigo3.py
I'm referencing this PR: https://github.com/CleoQc/GoPiGo3/pull/1
With this PR, the creation of a specific object is a lot more straightforward and easy.
This requires changing all the example programs accordingly.
=> sensor object getters for the easygopigo3 class

Software/Python/easygopigo3.py
Make the Turn X degrees block wait for completion.
=> Fix turn X degrees block, as an incentive to upgrade to 1.0.2

Software/Python/easygopigo3.py, docs/source/api-basic.rst, docs/source/quickstart.rst
This allows methods like lower() or upper() to be used especially when comparing with user input which needs to be cleaned. 
@RobertLucian  is this used anywhere yet? Or is it new enough that this change can be made?
=> change line follower readings to strictly lowercase 

Software/Python/easygopigo3.py
Support motion sensor as a digital sensor.
This may change in the future. 
Documentation included because good habits.
=> Motion Sensor support

Software/Python/easygopigo3.py
Also fix reach_inches to return one decimal
=> Distance sensor fix. Instantiation needs mutex

docs/source/devguide.rst
Added Matt as the creator of GoPiGo3 - which is what EasyGoPiGo3 is based on
Myself
Robert (who was already listed)
and John
=> Give more accurate attribution in the RTD developer section

Software/Python/Examples/easy_Buzzer.py, Software/Python/Examples/easy_Distance_Sensor.py, Software/Python/Examples/easy_Light_Sensor.py, docs/source/tutorials-basic/buzzer.rst, docs/source/tutorials-basic/light_sensor.rst
There were a few problems with them.  Working now, except for Distance Sensor.
=> Easy Examples Update

Software/Python/Examples/gps_reading.py
Also fixed a typo, because .. shudders...
=> fix print statements to be Python3 compatible (gps_readings.py)

Software/Go/readme.md
Adding a link to GoBot Go Language directory.
=> Adding link to GoBot.

Software/Python/easygopigo3.py
Solved issue as presented in https://forum.dexterindustries.com/t/servo-jams-with-reset-servo/3829
=> hotfix - reset_servo method in easygopigo3

Software/Python/easygopigo3.py
Am I seeing double or this library has two definitions for init_loudness_sensor()
=> Loudness sensor weird code

Software/Python/I2C_mutex.py, Software/Python/easygopigo3.py
Sometimes throwing an error because of inconsistent uses of tabs and spaces.
Now all spaces
=> Inconsistent tabs

Software/Python/easygopigo3.py
so when we expose the python in Bloxter it doesn't get too freaky
=> New method for line follower 

Projects/IntelligentObjectAvoider/README.md, Projects/IntelligentObjectAvoider/robot.py
This project is now fixed. 
It needs to be tested on an actual GoPiGo3 robot to be sure that it works.
This algorithm makes the robot scan the area with the distance sensor and the servo and then decides on an optimum path that gives the greatest distance to an object. This is how it operates:
1. Scan area with the "sonar".
2. Take best route.
3. Repeat.
=> fix - make the intelligent object avoider project work again

Install/README.md, Install/install.sh, Install/update_gopigo3.sh, README.md, docs/source/quickstart.rst
Again @mattallen37 thanks for having worked on this repository too. I have tested this one and seems to be going fine - followed the same procedure as with other robots too.
Once this is given the green light, we can change the source references to the final ones - for script_tools and for GoPiGo3.
=> feature - change how the installation of the robot goes

Install/update_gopigo3.sh
This reverts commit e82cb57c80559c5a6fe90f72321694d729d669e5.
This didn't seem to solve the issue. On systems where `git` is not installed, the update/install no longer gets through.
=> Revert "hotfix - install script_tools before rfr_tools (#189)"

Projects/RemoteCameraRobot/README.md, Projects/RemoteCameraRobot/install.sh
Fixing the installer script for the browser bot.
=> hotfix - browser bot project

Software/Python/easygopigo3.py, docs/source/conf.py, docs/source/quickstart.rst, docs/source/tutorials-basic/distance_sensor.rst
We have a couple of issues with our documentation that this PR fixes. 
Kind of a response to:
https://forum.dexterindustries.com/t/distance-sensor-inconsistency/3779/15
=> hotfix - distance sensor docs & others in the documentation

Projects/BasicRobotControl/README.md, Projects/CompassRobot/README.md, Projects/IntelligentObjectAvoider/README.md, Projects/IntelligentObjectAvoider/robot.py, Projects/MouseControl/README.md, Projects/ObjectAvoidanceRobot/README.md, Projects/ServoControl/README.md, Projects/ServoControl/keyboarded_robot.py
Changes brought in this PR:
1. Fixed the bug reported by [@cyclicalobsessive](https://forum.dexterindustries.com/u/cyclicalobsessive) where the position of the servo is updated before it's sent for further processing. He did give a thorough description in this [forum post](https://forum.dexterindustries.com/t/code-walkthrough-intelligentobjectavoider-two-angle-questions/5209).
1. Made the servo control project actually cut off the power to the servos when commanded so instead of just positioning the servos to their mid position. Requires https://github.com/DexterInd/GoPiGo3/pull/199.
1. Added READMEs for the rest of the GoPiGo3 projects except the Balance Bot which has been made by @mattallen37.
1. Added a note for DexterOS users in each of the projects' directory telling them that …
=> hotfix - fix multiple gopigo3 projects & add some READMEs

Install/README.md, Install/install.sh, Install/update_gopigo3.sh
Requires https://github.com/DexterInd/RFR_Tools/pull/13. With this new change, the GUI installation can be bypassed altogether.
=> hotfix - add gui option & optimize install script

Software/Python/easygopigo3.py, docs/source/api-basic/structure.rst, docs/source/conf.py
This fixes the couple of problems we had in https://github.com/DexterInd/GoPiGo3/pull/202. 
After we get this done, we can take the develop into the master branch.
=> fix - the documentation & update the copyright year

Firmware/gopigo3_flash_firmware.sh
As  per Matt's recommendation, slow down firmware update as it seems some GPG3 fail to upgrade their firmware otherwise.
=> slow down firmware update

Firmware/gopigo3_flash_firmware.sh
Slow down the speed to flash the firmware. 
This is taken live right away, no longer in dev.
=> hotfix/ fix firmware flashing speed

Software/Python/easygopigo3.py
This removes the need to call forward() after a change in set_speed() (from easygopigo3).
For now this PR is only for discussion as we think about potential side effects, if any.
=> For discussion: set methods to use high speed limit so limit is always from set_speed

.gitignore, Software/Scratch/GoPiGo3Scratch.py
Remove old implementation for the red line follower,
Use new implementation
=> Support Line Follower in Scratch

.gitignore, Software/Scratch/GoPiGo3Scratch.py
* Line follower moved to DI_Sensor Scratch
=> Support Line Follower in Scratch (#220)

Software/Python/easysensors.py
=> Remove errant print in read() method

Software/Python/easygopigo3.py, docs/source/api-basic/structure.rst
* Add parameter for EasyGoPiGo3 constructor that specifies the location of the configuration file for the 2 robot constants: the diameter of the wheels and the distance between the wheels. The robot has default values configured, but there may be cases where that isn't the case. 
* Add set/load/save methods for the 2 constants.
=> bring develop to master branch

Software/Csharp/README.md
Added documentation for .NET Core IoT in a specific folder with a Readme file with pointers on the source repository
=> Added documentation for .NET Core IoT

Software/Scratch/GoPiGo3Scratch.py
Add back support for the loudness sensor.
Introduce the use of the logging library instead of the clunky en_debug we used to have to the last few years.
Fix spaces (empty lines, wrong number of lines between functions - use "do not show whitespace changes" )
=> Support Loudness sensor

Software/NodeJS/src/gopigo3.js
I should have done this ages ago.
=> Fix firmware version in NodeJS

Software/Python/easysensors.py
As set_grove_pwm_duty() doesn't return a value, let's not assign it.
The documentation was already reflecting the proper situation, no return value.
=> Fix lack of return value

Projects/RemoteCameraRobot/requirements.txt
fixes https://github.com/DexterInd/GoPiGo3/issues/257
=> fix RemoteCameraRobot requirements

Install/antenna_wifi.sh
when on pure Raspbian, the color was too reddish, and it looked worrisome. Picked another colour.
=> change antenna color when on pure Raspbian

Software/Python/Examples/Control_Panel/control_panel_gui_3.py
Because of the move to Buster, wxpython is also moving in versions. Now need to deal with background color properly 
`self.SetBackgroundStyle(wx.BG_STYLE_CUSTOM)`  was a fix for previous versions.
=> fix bg color

Software/Python/tests/test_distance_sensor.py, Software/Python/tests/test_distance_sensor_2.py, Software/Python/tests/test_heavy_mutex_2.py
Answers https://github.com/DexterInd/GoPiGo3/issues/270
=> mix of tabs and spaces

Software/Python/easygopigo3.py
=> Fix readthedocs issue

Software/NodeJS/README.md
=> NodeJS readme changes

Software/Python/easygopigo3.py
user-reported issue when extending the easygopigo3 class.
=> change init call

Firmware/check_if_firmware_update_is_needed.py, Firmware/gopigo3_flash_firmware.sh, Software/Scratch/GoPiGo3Scratch.py
As we have been very stable in the firmware, let's avoid writing it when it's not needed. 
Also avoid writing the firmware when on a Pi4, as there are issues right now.
=> Avoid writing the firmware if update is not needed

README.md
Add info about GoPiGo OS in the readme file. 
Deprecate DexterOS
=> GoPiGo OS in Readme

Software/Python/gopigo3.py, docs/source/api-basic/structure.rst
Also a fix to the documentation, as robot constants are taken out of easygopigo3.
=> Fix edge condition for robot constants

Firmware/gopigo3_flash_firmware.sh, Firmware/rpi1.cfg, Firmware/rpi2.cfg, Firmware/rpi4-sysfsgpio.cfg, Software/Python/easygopigo3.py
Using sysfsgpio to flash firmware onto the GoPiGo, using a Pi4.
=> Firmware pi4
