DexterInd/GoPiGo3

Software/Python/easygopigo3.py
Handles the exceptions that may be raised from gopigo3.py
Major exceptions (like the GPG3 not being detected) are raised higher up. Others are handled at this level with a warning being printed but no tracebacks.
=> Bring easygopigo3 in line with current firmware and gopigo3

Software/Python/easygopigo3.py
Add a blocking test for the turn_degrees method.
Make blocking True by default. This has no impact on Bloxter, as all calls are explicitely stating that blocking is required but it will be nice to those who code in Python
=> fix turn block

Software/Python/easygopigo3.py, Software/Python/setup.py, docs/source/api-advanced.rst, docs/source/api-basic.rst, docs/source/quickstart.rst
Easygopigo3 can now be loaded up without the distance sensor, and from anywhere
IR Remote is now in easygopigo but in need of documentation. 
When user instantiates a sensor/actuator and doesn't pass a gpg value, an exception is now raise at instantiating time instead of crashing later on without a good error message.
too many commits are showing, only 2 files are changed
=> IR Remote, raise Exceptions when instantiating a sensor without a gpg

Software/Python/easygopigo3.py
Introduce a DEFAULT_SPEED variable set to 300 when __init__ is called.
reset_speed sets the speed without having to use a value. Easier to use as complexity is hidden from the user.
=> reset_speed() method

Software/Scratch/GoPiGo3Scratch.py
Distance sensor instantiation was changed and this wasn't kept up to date.
the gpg parameter must now be identified formally
(also removed from builtins at the top as it's not needed here and not installed by default on Raspbian per se)
=> [Scratch] Fix distance sensor instantiation and implement speed block for real

Software/Python/setup.py
As reported on this forum post:
https://forum.dexterindustries.com/t/python-lib-install-broken/3683
Even though this forum post refers to the `GrovePi` repo, it's the same issue as with the `GoPiGo3`.
After this gets approved, we need to push the changes to `PyPi`.
=> pip package can't get installed

Install/install.sh
This references this forum thread: https://forum.dexterindustries.com/t/failed-to-start-load-kernel-modules-and-no-wifi-interface-found/3587/20
=> spi-dev is not meant to be installed via the /etc/modules

Software/Python/easygopigo3.py
This is the change that's needed in easygopigo3 to handle the case where a line follower is not connected
=> raise error in line follower if the line follower is not connected

.gitmodules, docs/source/api-advanced.rst, docs/source/api-basic.rst, docs/source/conf.py, docs/source/devguide.rst, docs/source/faq.rst, docs/source/quickstart.rst
A built version of the updated documentation can be found here: http://gopigo3-dev.readthedocs.io
The link I have provided leads to an unlisted RTD project.
=> feature - [di-sensors] inclusion of documentation into the GPG3's + some touch-ups

README.md
The default version of the documentation has been changed and now we point to master.
As of this moment, we get an *Unknown documentation* error on our repo like in the following screenshot:
This PR solves this issue.
=> hotfix - docs badge updated

Software/Python/I2C_mutex.py
There is a tiny infinitesimal chance that DexterLockI2C_handle is equal to True, so let's handle this case.
([happened to at least one person](https://forum.dexterindustries.com/t/solved-distance-sensor-error/3822))
=> small fix in I2C_Mutex

Install/README.md, Install/install.sh, Install/update_gopigo3.sh, README.md, docs/source/quickstart.rst
This should make the GoPiGo3 update/install with or without privileges the python package(s).
For updating/installing the python packages of the GoPiGo3 **with** su privileges the user will run:
```
sudo sh -c "curl -kL dexterindustries.com/update_gopigo3 | bash"
curl -kL dexterindustries.com/update_gopigo3 > update_gopigo3.sh
sudo bash update_gopigo3.sh
```
For updating/installing the python packages of the GoPiGo3 **without** su privileges the user will run:
```
curl -kL dexterindustries.com/update_gopigo3 | bash
```
Further tests are still required before accepting this PR.
=> hotfix - root/non-root mechanism for installing/updating the gopigo3

docs/source/api-advanced.rst
: if importing easygopigo3, then importing gopigo3 is not required
=> small change to documentation

Projects/RemoteCameraRobot/install.sh
`wiringpi` seems to be needed on raspbian. I had encountered this when I tried to run the browser bot.
=> fix - adding missing dep to remotebot project

Software/C/CMakeLists.txt, Software/C/Examples/grove_led.cpp, Software/C/Examples/i2c.cpp, Software/C/Examples/info.cpp, Software/C/Examples/leds.cpp, Software/C/Examples/motors.cpp, Software/C/Examples/sensors.cpp, Software/C/GoPiGo3.cpp, Software/C/GoPiGo3.h, Software/C/gopigo3_cppConfig.cmake.in, Software/C/package.xml
This PR fixes the examples to include the GoPiGo3 header instead of the source file, cleans up `GoPiGo3.h` to only contain public functions used by examples, and adds a CMake build configuration and a ROS package definition.
Commits:
- renames example files from *.c to *.cpp
- moves function implementations to `GoPiGo3.cpp`
- moves internal function definitions (not used by examples) to `GoPiGo3.cpp`
- includes `GoPiGo3.h` in all examples and compiles with `GoPiGo3.cpp`
- adds a CMake build configuration for the library and examples
- adds a ROS package definition
=> CMake build configuration for C++ library

Software/Python/easygopigo3.py
If overall_mutex is set to True, the check we were making becomes meaningless. 
Also fix error message.
=> better handling of mutex checking

Software/C/GoPiGo3.cpp, Software/C/GoPiGo3.h, Software/Python/gopigo3.py
Add reset_motor_encoder to gopigo3.py as a simpler way to reset the encoders.
=> Add reset_motor_encoder

docs/source/conf.py
This doesn't have to be merged back into the dev branch as the dev branch follows a different route.
This fixes the documentation which no longer gets built, because `I2C_mutex` file has been removed in https://github.com/DexterInd/GoPiGo3/pull/165.
=> hotfix - mock I2C_mutex file

Install/install.sh
current DI Update leads to broken GoPiGo3 libraries.
I2C_Mutex used to be in easygopigo3 but now it's in its own library. However, old I2C_mutex was still being called from old libraries still around.
=> remove old libraries

Projects/RemoteCameraRobot/README.md, Projects/RemoteCameraRobot/install.sh, Projects/RemoteCameraRobot/install_startup.sh, Projects/RemoteCameraRobot/templates/index.html
My initial attempt was at making the browser bot work with the older packages from Jessie, since a quick search told me there's no support for Stretch for UV4L just yet - quite recent posts on various forums.
Unfortunately, I got into security and package incompatibility issues and that made me rethink the strategy as it had felt like a dead-end. Then I decided to dive a little more into seeing if there's someone who succeeded to make this work and surprisingly, I found that support for Stretch has just arrived not long ago. I used the new sources and it now works. 
The only caveat is that older versions for distributions such as jessie and wheezy are no longer maintained, but I don't think that's going to affect us in any way.
=> fix - browser bot project

docs/source/api-basic/structure.rst
Removing a duplicate in the documentation.
=> hotfix - remove a duplicate function in the docs

Software/Python/easysensors.py, docs/source/api-basic/structure.rst
Add a simple method to avoid making complex-and-hard-to-understand calls to disable a servo. Also, document it with docstrings.
=> feature - add kill power method for the servo

Software/Python/easysensors.py
Two improvements:
1. return sensor readings so that the left reading corresponds to the left sensor, in line follower.read()
read_raw_sensors() was left alone, as it clearly says it's raw readings. 
2. accelerate the read() method by *not* reading three files of the disk each time. Rather, remember the white and black calibrations as class members, and calculate threshold only when this calibration changes. 
DexterOS PR: https://github.com/DexterInd/Sam_Dev/pull/621 is dependent on this one.
=> Line follower improvements

Software/Python/easygopigo3.py
spin_left() and spin_right() make the GoPiGo3 pivot around its central axis.  
steer() lets you control each motor independently - which you could already do, this is just a wrapper.
orbit() will let you have the GoPiGo3 drive around an object for a certain arc length. You need to supply the radius in cm, and the arc length in degrees.  A radius of 0 will yield the same behaviour as either spin_left or spin_right.
=> new methods: spin_left, spin_right, steer and orbit

Software/Python/easygopigo3.py
After a call to orbit(), the dps was different on both wheels, leading to erratic behaviour.
=> reset speed after exiting from orbit

Software/Python/Examples/easy_Motors.py, docs/source/api-basic/structure.rst, docs/source/tutorials-basic/button.rst, docs/source/tutorials-basic/distance_sensor.rst, docs/source/tutorials-basic/driving.rst, docs/source/tutorials-basic/index.rst
Initially, I went with creating a separate chapter called `Tutorial - Driving` along with `Tutorial - Basic` and `Tutorial - Advanced`. There were 2 problems with it:
1. `Tutorial - Driving` would only have an index where one page would be shown. Not that many as in the `Basic` tutorials. A discrepancy thus appears.
1. Putting all these 3 chapters next to each other made `Tutorial - Driving` chapter look like an outsider - as if it's something that should have gone in the `Basic` tutorials' list. After all, the tutorial on driving the GoPiGo3 around is something easy to grasp and hence it should be in the `Tutorial - Basic` chapter.
Therefore, putting the `Driving the GoPiGo3 Around` tutorial in `Tutorial - Basic` chapter is more appropriate and it doesn't clutter our documentation - this …
=> feature - tutorial on driving around

docs/source/tutorials-basic/led.rst
To avoid confusion, I removed the deprecated way of instantiating an LED
=> Remove old fashioned way of  instantiating an LED in documentation

Software/Python/easygopigo3.py
I thought I had done this already, but it seems not. 
Needed for Python curriculum.
=> allow distance sensor to be on any port

Software/Python/easygopigo3.py, docs/source/api-basic/structure.rst
Add a couple of methods to EasyGoPiGo3 class to set/save/load the 2 constants of the GoPiGo3 (the wheel diameter and the base wheel width):
* `load_robot_constants` - loads the constants from file.
* `save_robot_constants` - saves constants to file.
* `set_robot_constants` - sets the 2 constants to the EasyGoPiGo3 object w/o saving them to file.
=> feature - config file for gopigo3 constants

Software/Scratch/GoPiGo3Scratch.py
Small error showing up if user closes Scratch directly.
Error introduced when I moved all print statements to logger statements.
=> Fix a runtime error

Software/Python/Examples/Control_Panel/control_panel_gui_3.py
STOP button in Remote Control was broken due to the variable 'process' not being initalized.
Also fix a few UI things, better alignment.
=> Fix STOP button

Firmware/gopigo3_flash_firmware.sh
This PR will only work if openOCD is also updated. The scripts are expected to keep them in sync.
=> allow RPi4 to flash firmware

Software/NodeJS/package.json
Not the Oxford comma but just as important.
=> Fix syntax in NodeJS/package.json

Projects/Connectome/Connectome.ipynb
It turns out that Jupyter notebooks don't like cells with 5000 lines.  In fact, less than 100 is better.
So I split all cells, and I optimized setting a dictionary to 0 on start.  It's still long to start but at least it won't crash the jupyter server. 
Did this for a specific client btw.
=> Optimize notebook

Software/Python/easygopigo3.py
Those methods were missing. It was expected that people would import from di_sensors, but that's clunky when you try to teach youngters. Also, only those two sensors were treated that way, not the distance sensor, nor the line following sensor for historical reasons. 
As for the try/except at the top, I went through the history and it looks like a bad merge.
=> init_light_color_sensor & init_imu_sensor

Install/gpg3_power.sh, Install/install.sh, Install/update_gopigo3.sh, Software/Python/Examples/Control_Panel/gopigo3_control_panel.desktop, Software/Python/gopigo3.py, Software/Scratch/start_local_scratch.sh
Use piGPIO instead.
start the daemon in the install script, and call pigpio when instantiating a gopigo3 to ensure pins are correct for SPI communications.
Also call Python2 and python3 explicitely to avoid mistakes.
=> Remove dependency on wiringPi

Software/Python/Examples/Control_Panel/control_panel_gui_3.py
The Wheel Base Width edit box cuts off the last digit of a WBW with two digit precision.  
This suggested change expands the edit box slightly to fully display WBW with two digits after the decimal.  
See Issue https://github.com/DexterInd/GoPiGo3/issues/286  for screen copy for before and after.
=> GoPiGo3 Control_Panel WBW edit box space for 2 digit precision

Software/Python/gopigo3.py
remove some print statements, and ignore the fact the gpg3_config.json may be missing. It's perfectly fine if it's missing, we just use the defaults.
=> Allow for missing gpg3_config.json

Software/Python/easygopigo3.py, Software/Python/gopigo3.py, Software/Python/setup.py
A call to pigpio.stop() is required, otherwise in multithreaded environments, or if a gopigo program is run multiple times one after the other, we end up with a pigpio complaint and the robot stops running.
Here's the pigpio error message that is taken care of with this PR:
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Can't connect to pigpio at localhost(8888)
Can't create callback thread.
Perhaps too many simultaneous pigpio connections.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
=> PiGPIO no longer leaking resources

Software/C/GoPiGo3.cpp
- shortened error string
- added return ERROR_NONE;
=> fix GoPiGo3.cpp warnings (Issue #322)

Software/C/CMakeLists.txt, Software/C/Examples/drive.cpp, Software/C/GoPiGo3.cpp, Software/C/GoPiGo3.h, Software/C/package.xml
=== Changes to C++ GoPiGo3 API
GoPiGo3.h
- Added Instance Variables:
- WHEEL_BASE_WIDTH, WHEEL_BASE_DIAMETER, ENCODER_TICKS_PER_ROTATION, MOTOR_GEAR_RATIO
- computed Instance Variables: WHEEL_BASE_CIRCUMFERENCE, WHEEL_CIRCUMFERENCE, MOTOR_TICKS_PER_DEGREE
- Added Declarations:
- check_serial_number_for_16_ticks()
- load_robot_constants()
- save_robot_constants()
- set_robot_constants()
- reset_motor_encoder()
GoPiGo3.cpp
- Added to GoPiGo3 object initialization:
- load_robot_constants()
- Added Definitions:
- check_serial_number_for_16_ticks()
- load_robot_constants()
- save_robot_constants()
- set_robot_constants()
- reset_motor_encoder()
Examples/
- Added drive.cpp: Drive GoPiGo3 using keyboard keys, showing encoder values
CMakeLists.txt
- Added Examples/drive.cpp
package.xml
- upped …
=> Add 16 tick support to C++ GoPiGo3 API, with drive GoPiGo3 example

Software/C/CMakeLists.txt, Software/C/Examples/drive.cpp, Software/C/Examples/servos.cpp, Software/C/Examples/vbatt.cpp, Software/C/GoPiGo3.cpp, Software/C/package.xml
- Modified set and get methods for motors and encoders to respect ENCODER_TICKS_PER_REVOLUTION and the resultant MOTOR_TICKS_PER_DEGREE.
- Added battery voltage and servos examples.
- Updated drive example with safe DPS limit.
- Bumped package version to 0.0.2
=> Completed GoPiGo3 C++ API support for 6 and 16 tick motors.  Two new C++ examples.
